# This is a basic workflow to help you get started with Actions

name: ONWFLOW_DOWNLOAD_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Metis from github
        run: |
          cd ${{ github.workspace }}
          ls
          mkdir download
          cd download
          git --version
          $project_url      = "https://github.com/eric2003/"
          $project_name     = "METIS-5.1.0-Modified"
          $project_git_name = $project_name + ".git"
          $project_web_addr = $project_url + $project_git_name
          git clone $project_web_addr
          ls
          cd $project_name
          ls
        shell: pwsh          
      - name: Download HDF5
        run: |
          cd ${{ github.workspace }}
          ls
          mkdir download1
          ls
        shell: pwsh          
